INSERT INTO PRODUCTS(ID, NAME, BRAND, DESCRIPTION, PRICE, QUANTITY) VALUES (801, '笔记本电脑','Oppo', 'Super fast laptop', 2000.0, 10);
INSERT INTO PRODUCTS(ID, NAME, BRAND, DESCRIPTION, PRICE, QUANTITY) VALUES (802, 'smartphone','XiaoMi', 'black cellphone', 1500.0, 32);
INSERT INTO PRODUCTS(ID, NAME, BRAND, DESCRIPTION, PRICE, QUANTITY) VALUES (803, 'video game','Apple-HP', 'old school video game', 1800.0, 2);
INSERT INTO PRODUCTS(ID, NAME, BRAND, DESCRIPTION, PRICE, QUANTITY) VALUES (804, 'smart tv','Vivo-Huawei', 'Big smart tv full of apps', 2000.0, 8);
INSERT INTO PRODUCTS(ID, NAME, BRAND, DESCRIPTION, PRICE, QUANTITY) VALUES (805, '鼠标','Logitech', 'just a mouse - not the animal :=P', 100.0, 16);
