spring:
  application:
    name: USER-SERVICE
  data:
    rest:
      base-path: api

  h2: 
    console: 
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  #zipkin:
  #  base-url: http://127.0.0.1:9411/
    #enabled: false

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
